modLoader="javafml"
loaderVersion="[41,)"
license="CC BY-NC-ND 4.0"
issueTrackerURL="https://github.com/tristankechlo/ToolLeveling/issues"
showAsResourcePack=false

[[mods]]
modId="toolleveling"
version="1.19 - 1.3.4"
displayName="Tool Leveling"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tool-leveling-plus"
logoFile="tool_leveling_banner.png"
#credits="Thanks for this example mod goes to Java"
authors="Buecher_wurm"
description='''adds the possibility to upgrade your enchantments higher than the vanilla limit'''

[[dependencies.toolleveling]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.95,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolleveling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"